### PR TITLE
Consistent look and feel

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by ericmann** [comment]
This really looks like refactoring for the sake of refactoring ... are these necessary changes or just personal preference?

**Comment by szepeviktor** [comment]
Absolutely no functional changes.
It is up to you.

**Comment by szepeviktor** [comment]
Maybe: easier to read.

**Comment by ericmann** [comment]
Closing for now. Appreciate the contribution, but feels extraneous.

**Pull request closed without merging**
